### ISSUE TITLE
config.properties (smp.config.properties)

### ISSUE THREAD

**Issue by skizub** [phax/phoss-smp#108]
Hi, 
we are setting up PHOSS SMP v 5.1.1 (XML backend).

Application is deployed in latest Apache Tomcat and UI is available online.

When starting tomcat - we are getting a following WARN/ERROR - see below:
-------------------------------------------------------------------------------------------------------------
2019-07-02 12:30:46,058 [INFO] eu.europa.ec.edelivery.smp.config.PropertiesConfig  - Start read file properties from '/smp.config.properties'
2019-07-02 12:30:46,058 [INFO] eu.europa.ec.edelivery.smp.config.PropertiesConfig  - File '/smp.config.properties' not found in classpath, read '/config.properties'
2019-07-02 12:30:46,059 [INFO] eu.europa.ec.edelivery.smp.config.PropertiesConfig  - Start database properties
2019-07-02 12:30:46,061 [INFO] eu.europa.ec.edelivery.smp.config.PropertiesConfig  - Connect to jdbc:h2:file:./target/myDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=TRUE.
2019-07-02 12:30:46,065 [WARN] org.springframework.web.context.support.AnnotationConfigWebApplicationContext  - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'propertySourcesPlaceholderConfigurer' defined in eu.europa.ec.edelivery.smp.config.PropertiesConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.context.support.PropertySourcesPlaceholderConfigurer]: Factory method 'propertySourcesPlaceholderConfigurer' threw exception; nested exception is java.lang.IllegalStateException: Could not load JDBC driver class [org.h2.Driver]
2019-07-02 12:30:46,074 [ERROR] org.springframework.web.context.ContextLoader  - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'propertySourcesPlaceholderConfigurer' defined in eu.europa.ec.edelivery.smp.config.PropertiesConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.context.support.PropertySourcesPlaceholderConfigurer]: Factory method 'propertySourcesPlaceholderConfigurer' threw exception; nested exception is java.lang.IllegalStateException: Could not load JDBC driver class [org.h2.Driver]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:625)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:455)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)

Is that something we need to worry about?
Is file config.properties containing a reference to H2 JDBC something we need to configure additionally?

**Comment by phax** [comment]
@skizub These are not the logs from phoss SMP - phoss SMP ships without Spring Framework :) This looks like the CEF SMP.... Does that sound reasonable to you?

**Comment by skizub** [comment]
@phax - yes makes a perfect sense:) - feel free to close this query.

**Comment by phax** [comment]
Thanks for the quick response. Good luck with the resolution
