### ISSUE TITLE
Update Business Card ssl handshake failure v5.2.1 (test)

### ISSUE THREAD

**Issue by sanderverhoeven** [phax/phoss-smp#124]
URL: https://smp.develop.calvi-insight.com/
Certificate in pd-client.properties is the same as smp-server.properties as described in https://github.com/phax/phoss-smp/wiki/Configuration.

Trace of stdout:

`[2020-02-06T14:38:58,434] [SMP-SERVER] [ERROR] [http-nio-8080-exec-3] Internal error in addServiceGroupToIndex for iso6523-actorid-upis::0106:17133645 -- com.helger.pd.client.PDClient.lambda$_createDefaultExCb$5f881514$1(PDClient.java:67)
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
        at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:308) ~[?:?]
        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:285) ~[?:?]
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:181) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1155) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1125) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823) ~[?:?]
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[httpcore-4.4.12.jar:4.4.12]
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[httpcore-4.4.12.jar:4.4.12]
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280) ~[httpcore-4.4.12.jar:4.4.12]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[httpclient-4.5.10.jar:4.5.10]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[httpclient-4.5.10.jar:4.5.10]
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.12.jar:4.4.12]
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[httpcore-4.4.12.jar:4.4.12]
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) ~[httpclient-4.5.10.jar:4.5.10]
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[httpcore-4.4.12.jar:4.4.12]
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore-4.4.12.jar:4.4.12]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[httpclient-4.5.10.jar:4.5.10]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.10.jar:4.5.10]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.10.jar:4.5.10]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.10.jar:4.5.10]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.10.jar:4.5.10]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.10.jar:4.5.10]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221) ~[httpclient-4.5.10.jar:4.5.10]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165) ~[httpclient-4.5.10.jar:4.5.10]
        at com.helger.httpclient.HttpClientManager.execute(HttpClientManager.java:192) ~[ph-httpclient-9.1.5.jar:9.1.5]
        at com.helger.pd.client.PDClient.executeRequest(PDClient.java:253) ~[phoss-directory-client-0.8.4.jar:0.8.4]
        at com.helger.pd.client.PDClient.addServiceGroupToIndex(PDClient.java:293) ~[phoss-directory-client-0.8.4.jar:0.8.4]
        at com.helger.phoss.smp.ui.secure.PageSecureBusinessCard$2.handleAction(PageSecureBusinessCard.java:237) ~[phoss-smp-webapp-5.2.1.jar:5.2.1]
        at com.helger.phoss.smp.ui.secure.PageSecureBusinessCard$2.handleAction(PageSecureBusinessCard.java:227) ~[phoss-smp-webapp-5.2.1.jar:5.2.1]
        at com.helger.photon.uicore.page.AbstractWebPageForm.fillContent(AbstractWebPageForm.java:1342) ~[ph-oton-uicore-8.2.1.jar:8.2.1]
        at com.helger.photon.uicore.page.AbstractWebPage.getContent(AbstractWebPage.java:160) ~[ph-oton-uicore-8.2.1.jar:8.2.1]
        at com.helger.phoss.smp.ui.pub.SMPRendererPublic.getPageContent(SMPRendererPublic.java:259) ~[phoss-smp-webapp-5.2.1.jar:5.2.1]
        at com.helger.phoss.smp.ui.secure.SMPRendererSecure.getContent(SMPRendererSecure.java:208) ~[phoss-smp-webapp-5.2.1.jar:5.2.1]
        at com.helger.phoss.smp.ui.SMPLayoutHTMLProvider.fillBody(SMPLayoutHTMLProvider.java:70) [phoss-smp-webapp-5.2.1.jar:5.2.1]
        at com.helger.photon.core.html.AbstractSWECHTMLProvider.fillHeadAndBody(AbstractSWECHTMLProvider.java:107) [ph-oton-core-8.2.1.jar:8.2.1]
        at com.helger.photon.core.html.AbstractHTMLProvider.createHTML(AbstractHTMLProvider.java:166) [ph-oton-core-8.2.1.jar:8.2.1]
        at com.helger.photon.app.html.PhotonHTMLHelper.createHTMLResponse(PhotonHTMLHelper.java:116) [ph-oton-app-8.2.1.jar:8.2.1]
        at com.helger.photon.core.servlet.AbstractApplicationXServletHandler.handleRequest(AbstractApplicationXServletHandler.java:91) [ph-oton-core-8.2.1.jar:8.2.1]
        at com.helger.xservlet.handler.simple.XServletHandlerToSimpleHandler.onRequest(XServletHandlerToSimpleHandler.java:245) [ph-xservlet-9.1.5.jar:9.1.5]
        at com.helger.xservlet.AbstractXServlet._invokeHandler(AbstractXServlet.java:351) [ph-xservlet-9.1.5.jar:9.1.5]
        at com.helger.xservlet.AbstractXServlet.service(AbstractXServlet.java:537) [ph-xservlet-9.1.5.jar:9.1.5]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
        at com.helger.xservlet.AbstractXServlet.service(AbstractXServlet.java:592) [ph-xservlet-9.1.5.jar:9.1.5]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.20]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.20]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.20]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.20]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.20]
        at com.helger.web.servlets.scope.AbstractScopeAwareFilter.doHttpFilter(AbstractScopeAwareFilter.java:83) [ph-web-9.1.5.jar:9.1.5]
        at com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66) [ph-servlet-9.1.5.jar:9.1.5]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.20]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.20]
        at com.helger.xservlet.AbstractXFilter.doHttpFilter(AbstractXFilter.java:189) [ph-xservlet-9.1.5.jar:9.1.5]
        at com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66) [ph-servlet-9.1.5.jar:9.1.5]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.20]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.20]
        at com.helger.servlet.filter.CharacterEncodingFilter.doHttpFilter(CharacterEncodingFilter.java:187) [ph-servlet-9.1.5.jar:9.1.5]
        at com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66) [ph-servlet-9.1.5.jar:9.1.5]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.20]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.20]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200) [catalina.jar:9.0.20]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.20]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [catalina.jar:9.0.20]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.20]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.20]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [catalina.jar:9.0.20]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.20]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.20]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-coyote.jar:9.0.20]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.20]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836) [tomcat-coyote.jar:9.0.20]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1839) [tomcat-coyote.jar:9.0.20]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.20]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.20]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[2020-02-06T14:40:45,957] [SMP-SERVER] [WARN ] [http-nio-8080-exec-7] System property 'java.endorsed.dirs' is not set! -- com.helger.commons.system.SystemProperties.getPropertyValue(SystemProperties.java:108)
[2020-02-06T14:40:45,960] [SMP-SERVER] [WARN ] [http-nio-8080-exec-7] System property 'java.ext.dirs' is not set! -- com.helger.commons.system.SystemProperties.getPropertyValue(SystemProperties.java:108)`

I have added the latest complete_truststore.jks. 
We only support TLS1.2 any ideas?

**Comment by phax** [comment]
Hi,
is it possible that you maintained the "old" complete trusstore in your SMP?
There was a time, when I accidentally included the "Lets Encrypt certificate" of Peppol Directory in the truststore, but that made no sense.
Can you please crosscheck if your "complete_truststore.jks" matches the one available at https://github.com/phax/peppol-commons/tree/master/peppol-commons/src/main/resources/truststore ??
TLS 1.2 should not be an issue.
hth, Philip

**Comment by phax** [comment]
Inside the tool there is a "Certificate Information" page. Go to the "Truststore" tab and check if a "Let's Encrypt" certificate is contained. If so, please update your trust store.

**Comment by sanderverhoeven** [comment]
I will check the truststore. I see the "Lets Encrypt certificate". will remove it from the store. let you know if it works after that.

**Comment by phax** [comment]
Please check the reference in the "pd-client.properties" and "smp-server.properties". They should reference the same keystore and truststore.
The "complete_truststore.jks" is usually "hidden" in the classpath - it is part of "peppol-commons-x.y.z.jar"

**Comment by phax** [comment]
@sanderverhoeven Did you manage to resolve this issue?

**Comment by sanderverhoeven** [comment]
Hi, I did not resolve it yes, although no let's encrypt certificate is in the trust store and the properties files are checked. still a handshake failure. I will try to receive the stack trace today.

**Comment by phax** [comment]
Shall we have a short skype call where you can share screen?

**Comment by sanderverhoeven** [comment]
Philip thank you for the great support. the solution we came up with was the alias of the jks key store. For pd-client the client certificate alias is treated case sensitive.
