### ISSUE TITLE
SECURITY - CP: , Cert: null

### ISSUE THREAD

**Issue by convicteva** [phax/phoss-smp#189]
LoggerSecurityImpl:49 - [SECURITY - CP: , Cert: null, Client-Cert: null, Admin-Pwd: null/empty/blank, SSLCert: null] null
LoggingServiceImpl:99 - eu.europa.ec.bdmsl.security.UnsecureAuthentication cannot be cast to eu.europa.ec.bdmsl.security.CertificateAuthentication
java.lang.ClassCastException: eu.europa.ec.bdmsl.security.UnsecureAuthentication cannot be cast to eu.europa.ec.bdmsl.security.CertificateAuthentication
 at eu.europa.ec.bdmsl.business.impl.ManageServiceMetadataBusinessImpl.createSMP(ManageServiceMetadataBusinessImpl.java:190) ~[classes/]
 at eu.europa.ec.bdmsl.service.impl.ManageServiceMetadataServiceImpl.create(ManageServiceMetadataServiceImpl.java:88) ~[classes/]
 at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source) ~[?]

BDMSL version：4.1.0
phoss-smp ：5.4.5 」

**Comment by phax** [comment]
Hi, That seems to be a Classloader issue.
Can you try running the SMP in its own Tomcat????
