### ISSUE TITLE
Unable to create Business Card: Found no certificate alias matching

### ISSUE THREAD

**Issue by ashleyecloud** [phax/phoss-smp#212]
What truststore/keystore is it referring to where "Found no certificate alias matching 'REDACTED'"?

```[2022-04-05T05:55:43,399] [SMP-SERVER] [INFO ] [http-nio-8080-exec-8] PD client uses disabled hostname verification -- com.helger.pd.client.PDHttpClientSettings.resetToConfiguration(PDHttpClientSettings.java:109)
[2022-04-05T05:55:43,408] [SMP-SERVER] [INFO ] [http-nio-8080-exec-8] PD client keystore successfully loaded -- com.helger.pd.client.PDHttpClientSettings.resetToConfiguration(PDHttpClientSettings.java:122)
[2022-04-05T05:55:43,413] [SMP-SERVER] [INFO ] [http-nio-8080-exec-8] PD client key successfully loaded -- com.helger.pd.client.PDHttpClientSettings.resetToConfiguration(PDHttpClientSettings.java:132)
[2022-04-05T05:55:43,413] [SMP-SERVER] [INFO ] [http-nio-8080-exec-8] PD client truststore successfully loaded -- com.helger.pd.client.PDHttpClientSettings.resetToConfiguration(PDHttpClientSettings.java:141)
[20power22-04-05T05:55:43,469] [SMP-SERVER] [INFO ] [http-nio-8080-exec-8] PD client successfully set SSL context -- com.helger.pd.client.PDHttpClientSettings.resetToConfiguration(PDHttpClientSettings.java:151)
[2022-04-05T05:55:46,363] [SMP-SERVER] [WARN ] [http-nio-8080-exec-8] Found no certificate alias matching 'REDACTED' in the provided aliases [] -- com.helger.httpclient.security.PrivateKeyStrategyFromAliasCaseInsensitive.chooseAlias(PrivateKeyStrategyFromAliasCaseInsensitive.java:104)
[2022-04-05T05:55:46,363] [SMP-SERVER] [WARN ] [http-nio-8080-exec-8] Found no certificate alias matching 'REDACTED' in the provided aliases [] -- com.helger.httpclient.security.PrivateKeyStrategyFromAliasCaseInsensitive.chooseAlias(PrivateKeyStrategyFromAliasCaseInsensitive.java:104)
[2022-04-05T05:55:46,364] [SMP-SERVER] [WARN ] [http-nio-8080-exec-8] Found no certificate alias matching 'REDACTED' in the provided aliases [] -- com.helger.httpclient.security.PrivateKeyStrategyFromAliasCaseInsensitive.chooseAlias(PrivateKeyStrategyFromAliasCaseInsensitive.java:104)
[2022-04-05T05:55:46,364] [SMP-SERVER] [WARN ] [http-nio-8080-exec-8] Found no certificate alias matching 'REDACTED' in the provided aliases [] -- com.helger.httpclient.security.PrivateKeyStrategyFromAliasCaseInsensitive.chooseAlias(PrivateKeyStrategyFromAliasCaseInsensitive.java:104)
[2022-04-05T05:55:46,364] [SMP-SERVER] [WARN ] [http-nio-8080-exec-8] Found no certificate alias matching 'REDACTED' in the provided aliases [] -- com.helger.httpclient.security.PrivateKeyStrategyFromAliasCaseInsensitive.chooseAlias(PrivateKeyStrategyFromAliasCaseInsensitive.java:104)
[2022-04-05T05:55:46,364] [SMP-SERVER] [WARN ] [http-nio-8080-exec-8] Found no certificate alias matching 'REDACTED' in the provided aliases [] -- com.helger.httpclient.security.PrivateKeyStrategyFromAliasCaseInsensitive.chooseAlias(PrivateKeyStrategyFromAliasCaseInsensitive.java:104)
[2022-04-05T05:55:46,368] [SMP-SERVER] [WARN ] [http-nio-8080-exec-8] Found no certificate alias matching 'REDACTED' in the provided aliases [] -- com.helger.httpclient.security.PrivateKeyStrategyFromAliasCaseInsensitive.chooseAlias(PrivateKeyStrategyFromAliasCaseInsensitive.java:104)
[2022-04-05T05:55:46,369] [SMP-SERVER] [WARN ] [http-nio-8080-exec-8] Found no certificate alias matching 'REDACTED' in the provided aliases [] -- com.helger.httpclient.security.PrivateKeyStrategyFromAliasCaseInsensitive.chooseAlias(PrivateKeyStrategyFromAliasCaseInsensitive.java:104)
[2022-04-05T05:55:46,369] [SMP-SERVER] [WARN ] [http-nio-8080-exec-8] Found no certificate alias matching 'REDACTED' in the provided aliases [] -- com.helger.httpclient.security.PrivateKeyStrategyFromAliasCaseInsensitive.chooseAlias(PrivateKeyStrategyFromAliasCaseInsensitive.java:104)
[2022-04-05T05:55:46,369] [SMP-SERVER] [WARN ] [http-nio-8080-exec-8] Found no certificate alias matching 'REDACTED' in the provided aliases [] -- com.helger.httpclient.security.PrivateKeyStrategyFromAliasCaseInsensitive.chooseAlias(PrivateKeyStrategyFromAliasCaseInsensitive.java:104)
[2022-04-05T05:55:46,369] [SMP-SERVER] [WARN ] [http-nio-8080-exec-8] Found no certificate alias matching 'REDACTED' in the provided aliases [] -- com.helger.httpclient.security.PrivateKeyStrategyFromAliasCaseInsensitive.chooseAlias(PrivateKeyStrategyFromAliasCaseInsensitive.java:104)
[2022-04-05T05:55:46,369] [SMP-SERVER] [WARN ] [http-nio-8080-exec-8] Found no certificate alias matching 'REDACTED' in the provided aliases [] -- com.helger.httpclient.security.PrivateKeyStrategyFromAliasCaseInsensitive.chooseAlias(PrivateKeyStrategyFromAliasCaseInsensitive.java:104)
[2022-04-05T05:55:46,369] [SMP-SERVER] [WARN ] [http-nio-8080-exec-8] Found no certificate alias matching 'REDACTED' in the provided aliases [] -- com.helger.httpclient.security.PrivateKeyStrategyFromAliasCaseInsensitive.chooseAlias(PrivateKeyStrategyFromAliasCaseInsensitive.java:104)
[2022-04-05T05:55:46,673] [SMP-SERVER] [ERROR] [http-nio-8080-exec-8] Internal error in addServiceGroupToIndex for iso6523-actorid-upis::0088:REDACTED -- com.helger.pd.client.PDClient.lambda$_createDefaultExCb$0(PDClient.java:62)
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
        at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:339) ~[?:?]
        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293) ~[?:?]
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1504) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1471) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1060) ~[?:?]
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[httpcore-4.4.15.jar:4.4.15]
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[httpcore-4.4.15.jar:4.4.15]
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280) ~[httpcore-4.4.15.jar:4.4.15]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.15.jar:4.4.15]
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[httpcore-4.4.15.jar:4.4.15]
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[httpcore-4.4.15.jar:4.4.15]
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore-4.4.15.jar:4.4.15]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165) ~[httpclient-4.5.13.jar:4.5.13]
        at com.helger.httpclient.HttpClientManager.execute(HttpClientManager.java:190) ~[ph-httpclient-9.6.3.jar:9.6.3]
        at com.helger.httpclient.HttpClientManager.execute(HttpClientManager.java:155) ~[ph-httpclient-9.6.3.jar:9.6.3]
        at com.helger.pd.client.PDClient.executeRequest(PDClient.java:210) ~[phoss-directory-client-0.9.9.jar:0.9.9]
        at com.helger.pd.client.PDClient.addServiceGroupToIndex(PDClient.java:250) ~[phoss-directory-client-0.9.9.jar:0.9.9]
        at com.helger.phoss.smp.ui.secure.PageSecureBusinessCard$2.handleAction(PageSecureBusinessCard.java:241) ~[phoss-smp-webapp-5.6.2.jar:5.6.2]
        at com.helger.phoss.smp.ui.secure.PageSecureBusinessCard$2.handleAction(PageSecureBusinessCard.java:216) ~[phoss-smp-webapp-5.6.2.jar:5.6.2]
        at com.helger.photon.uicore.page.AbstractWebPageForm.fillContent(AbstractWebPageForm.java:1326) ~[ph-oton-uicore-8.3.6.jar:8.3.6]
        at com.helger.photon.uicore.page.AbstractWebPage.getContent(AbstractWebPage.java:162) ~[ph-oton-uicore-8.3.6.jar:8.3.6]
        at com.helger.photon.bootstrap4.uictrls.ext.BootstrapPageRenderer.getPageContent(BootstrapPageRenderer.java:133) ~[ph-oton-bootstrap4-uictrls-8.3.6.jar:8.3.6]
        at com.helger.photon.bootstrap4.uictrls.ext.BootstrapPageRenderer.getPageContent(BootstrapPageRenderer.java:160) ~[ph-oton-bootstrap4-uictrls-8.3.6.jar:8.3.6]
        at com.helger.phoss.smp.ui.secure.SMPRendererSecure.getContent(SMPRendererSecure.java:215) ~[phoss-smp-webapp-5.6.2.jar:5.6.2]
        at com.helger.phoss.smp.ui.SMPLayoutHTMLProvider.fillBody(SMPLayoutHTMLProvider.java:70) [phoss-smp-webapp-5.6.2.jar:5.6.2]
        at com.helger.photon.core.html.AbstractSWECHTMLProvider.fillHeadAndBody(AbstractSWECHTMLProvider.java:104) [ph-oton-core-8.3.6.jar:8.3.6]
        at com.helger.photon.core.html.AbstractHTMLProvider.createHTML(AbstractHTMLProvider.java:164) [ph-oton-core-8.3.6.jar:8.3.6]
        at com.helger.photon.app.html.PhotonHTMLHelper.createHTMLResponse(PhotonHTMLHelper.java:117) [ph-oton-app-8.3.6.jar:8.3.6]
        at com.helger.photon.core.servlet.AbstractApplicationXServletHandler.handleRequest(AbstractApplicationXServletHandler.java:101) [ph-oton-core-8.3.6.jar:8.3.6]
        at com.helger.phoss.smp.servlet.SMPApplicationXServletHandler.handleRequest(SMPApplicationXServletHandler.java:81) [phoss-smp-webapp-5.6.2.jar:5.6.2]
        at com.helger.xservlet.handler.simple.XServletHandlerToSimpleHandler.onRequest(XServletHandlerToSimpleHandler.java:245) [ph-xservlet-9.6.3.jar:9.6.3]
        at com.helger.xservlet.AbstractXServlet._invokeHandler(AbstractXServlet.java:345) [ph-xservlet-9.6.3.jar:9.6.3]
        at com.helger.xservlet.AbstractXServlet.service(AbstractXServlet.java:533) [ph-xservlet-9.6.3.jar:9.6.3]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [servlet-api.jar:4.0.FR]
        at com.helger.xservlet.AbstractXServlet.service(AbstractXServlet.java:587) [ph-xservlet-9.6.3.jar:9.6.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [catalina.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.60]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.60]
        at com.helger.web.servlets.scope.AbstractScopeAwareFilter.doHttpFilter(AbstractScopeAwareFilter.java:81) [ph-web-9.6.3.jar:9.6.3]
        at com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66) [ph-servlet-9.6.3.jar:9.6.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.60]
        at com.helger.xservlet.AbstractXFilter.doHttpFilter(AbstractXFilter.java:189) [ph-xservlet-9.6.3.jar:9.6.3]
        at com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66) [ph-servlet-9.6.3.jar:9.6.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.60]
        at com.helger.servlet.filter.CharacterEncodingFilter.doHttpFilter(CharacterEncodingFilter.java:187) [ph-servlet-9.6.3.jar:9.6.3]
        at com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66) [ph-servlet-9.6.3.jar:9.6.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.60]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.60]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [catalina.jar:9.0.60]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:9.0.60]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.60]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [catalina.jar:9.0.60]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.60]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [catalina.jar:9.0.60]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:9.0.60]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) [catalina.jar:9.0.60]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat-coyote.jar:9.0.60]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.60]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) [tomcat-coyote.jar:9.0.60]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) [tomcat-coyote.jar:9.0.60]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.60]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:9.0.60]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.60]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.60]
        at java.lang.Thread.run(Thread.java:829) [?:?]
rapperValve.invoke(StandardWrapperValve.java:197) [catalina.jar:9.0.60]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:9.0.60]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.60]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [catalina.jar:9.0.60]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.60]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [catalina.jar:9.0.60]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:9.0.60]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) [catalina.jar:9.0.60]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat-coyote.jar:9.0.60]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.60]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) [tomcat-coyote.jar:9.0.60]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) [tomcat-coyote.jar:9.0.60]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.60]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:9.0.60]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.60]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.60]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by phax** [comment]
Hi @ashleyecloud, thanks for reaching out to me.
Most likely your "trust store contains out of date" certificates.
Please have a look at the discussion https://github.com/phax/phoss-smp/discussions/211#discussioncomment-2653792 that deals with the same issue and should resolve your issue as well.

**Comment by ashleyecloud** [comment]
@phax Using the complete-truststore.jks for "Peppol Directory Truststore" - I still get the same error  
Do I need to modify the complete-truststore.jks in anyway?  
  
```
Found no certificate alias matching 'REDACTED' in the provided aliases [] -- com.helger.httpclient.security.PrivateKeyStrategyFromAliasCaseInsensitive.chooseAlias(PrivateKeyStrategyFromAliasCaseInsensitive.java:104)
```

The REDACTED part is my business name, not sure what I'm doing wrong.

**Comment by phax** [comment]
Okay. You should never modify the truststore.
My assumption is, that you did not configure the keystore correctly.
In the configuration file `application.properties` (old name `pd-client.properties`) please make sure, you are using the same SMP keystore than in your main `smp-server.properties` file.
The SMP certificate is used as a client certificate to the Directory

**Comment by ashleyecloud** [comment]
My PEPPOL Directory keystore was not configured correctly, it is now fixed. Thanks!
