### ISSUE TITLE
Unable to create/update/delete Identifier on SMK Lately - The server sent HTTP status code 401: Unauthorized

### ISSUE THREAD

**Issue by duke-nuke** [phax/phoss-smp#214]
Hi Team
I am using SMP version is (SMP and AP 5.5.0-SNAPSHOT) with database postgresql and 
trying to create Identifier on SMK but failed with the following error
The server sent HTTP status code 401: Unauthorized 

earlier it was working fine from last two years not sure if SMK has implemented any Authentication on SMK, SML is working fine
you can find stack trace below

[DEBUG] 2022-05-19 10:59:38.291 [qtp1174586025-16] SMPServiceGroupManagerJDBC - getSMPServiceGroupOfID(iso6523-actorid-upis::0151:12234)
[INFO ] 2022-05-19 10:59:38.292 [qtp1174586025-16] RegistrationHookWriteToSML - Trying to DELETE business iso6523-actorid-upis::0151:12234 for .......... from SML
[INFO ] 2022-05-19 10:59:38.293 [qtp1174586025-16] RegistrationHookWriteToSML - Performing SML query to 'https://acc.edelivery.tech.ec.europa.eu/edelivery-sml/manageparticipantidentifier'
[WARN ] 2022-05-19 10:59:39.509 [qtp1174586025-16] SMPCommonUI - Technical details
com.helger.phoss.smp.smlhook.RegistrationHookException: Could not delete business iso6523-actorid-upis::0151:12234 from SML.
        at com.helger.phoss.smp.smlhook.RegistrationHookWriteToSML.deleteServiceGroup(RegistrationHookWriteToSML.java:187) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.phoss.smp.ui.secure.PageSecureServiceGroup$4.handleAction(PageSecureServiceGroup.java:353) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.phoss.smp.ui.secure.PageSecureServiceGroup$4.handleAction(PageSecureServiceGroup.java:343) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.photon.uicore.page.AbstractWebPageForm.fillContent(AbstractWebPageForm.java:1326) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.photon.uicore.page.AbstractWebPage.getContent(AbstractWebPage.java:162) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.photon.bootstrap4.uictrls.ext.BootstrapPageRenderer.getPageContent(BootstrapPageRenderer.java:133) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.photon.bootstrap4.uictrls.ext.BootstrapPageRenderer.getPageContent(BootstrapPageRenderer.java:160) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.phoss.smp.ui.secure.SMPRendererSecure.getContent(SMPRendererSecure.java:215) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.phoss.smp.ui.SMPLayoutHTMLProvider.fillBody(SMPLayoutHTMLProvider.java:70) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.photon.core.html.AbstractSWECHTMLProvider.fillHeadAndBody(AbstractSWECHTMLProvider.java:104) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.photon.core.html.AbstractHTMLProvider.createHTML(AbstractHTMLProvider.java:164) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.photon.app.html.PhotonHTMLHelper.createHTMLResponse(PhotonHTMLHelper.java:117) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.photon.core.servlet.AbstractApplicationXServletHandler.handleRequest(AbstractApplicationXServletHandler.java:100) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.phoss.smp.servlet.SMPApplicationXServletHandler.handleRequest(SMPApplicationXServletHandler.java:81) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.xservlet.handler.simple.XServletHandlerToSimpleHandler.onRequest(XServletHandlerToSimpleHandler.java:245) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.xservlet.AbstractXServlet._invokeHandler(AbstractXServlet.java:345) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.xservlet.AbstractXServlet.service(AbstractXServlet.java:529) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.xservlet.AbstractXServlet.service(AbstractXServlet.java:583) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.web.servlets.scope.AbstractScopeAwareFilter.doHttpFilter(AbstractScopeAwareFilter.java:81) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.xservlet.AbstractXFilter.doHttpFilter(AbstractXFilter.java:189) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.servlet.filter.CharacterEncodingFilter.doHttpFilter(CharacterEncodingFilter.java:187) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) [peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) [peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386) [peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: com.sun.xml.ws.client.ClientTransportException: The server sent HTTP status code 401: Unauthorized
        at com.sun.xml.ws.transport.http.client.HttpTransportPipe.checkStatusCode(HttpTransportPipe.java:302) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.sun.xml.ws.transport.http.client.HttpTransportPipe.createResponsePacket(HttpTransportPipe.java:244) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.sun.xml.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:202) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.sun.xml.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:115) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.sun.xml.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:109) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1106) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1020) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:989) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:847) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.sun.xml.ws.client.Stub.process(Stub.java:433) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.sun.xml.ws.client.sei.SEIStub.doProcess(SEIStub.java:161) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:62) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:131) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.sun.proxy.$Proxy63.delete(Unknown Source) ~[?:?]
        at com.helger.peppol.smlclient.ManageParticipantIdentifierServiceCaller.delete(ManageParticipantIdentifierServiceCaller.java:286) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.peppol.smlclient.ManageParticipantIdentifierServiceCaller.delete(ManageParticipantIdentifierServiceCaller.java:256) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at com.helger.phoss.smp.smlhook.RegistrationHookWriteToSML.deleteServiceGroup(RegistrationHookWriteToSML.java:175) ~[peppol-smp-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        ... 65 more

**Comment by duke-nuke** [comment]
Any Operation by SMP on SML is resulting in the above error.

**Comment by phax** [comment]
Hi @duke-nuke,
According to my Wiki cheat sheet at https://github.com/phax/phoss-smp/wiki/SML-notes it means "User unauthorized".
Did you eventually, recently change/renew your certificate?
Or did you change your SMP ID?
What happened on your side between now and the last time it worked?
hth, Philip

**Comment by duke-nuke** [comment]
certificates were updated but seems everything worked after that upgrade,
recently the IP of of the machine running SMP was changed, but i have host SMP through apache proxy and registered the SMK with that IP

**Comment by phax** [comment]
Okay, did you follow the update process described at https://peppol.helger.com/public/locale-en_US/menuitem-docs-peppol-cert-update ???

**Comment by phax** [comment]
That should not be a problem at all - I am aware of similar setup that works without problem.
Is is possible that your application mix the SMP ID and the SML they are registered to? The test server should contain ".acc" (for acceptance) whereas the production server does not contain ".acc".
Eventually please send me a PM with your SMP URLs and I can do q auick check. See /pom.xml for my email address.

**Comment by duke-nuke** [comment]
Thanks Phax 
i contacted CEF support, they are saying the certificate is not updated on their end, you were right that this is a certificate issue, 

on SML i am having this issue it is showing DNS resolved failed for service groups, what could be an issue?
![image](https://user-images.githubusercontent.com/3961663/169637627-7ba603ae-2e2c-4ec9-bdd2-9fbb85e312a2.png)


Thanks for your reply and help

**Comment by phax** [comment]
Well, it seems like you did "unregister" your SMP from the SML? That means you lost all Service Group registrations.
So this information seems to be real!
Please elaborate what you did

**Comment by duke-nuke** [comment]
I did nothing, i just tried to Update SMK and once tried delete SMK but everytime i got 401 Unauthorized exception for SMK. 
for SML i just updated SML to previous information, but if i click on Register in SML i get Bad request.

**Comment by phax** [comment]
Okay, but now you received instructions from CEF how to do it, right?
They are updating the certificate information for you...
Can you please post a participant identifier for which you are sure, that it should be registered on your test SMP - thx.
