### ISSUE TITLE
com.sun.xml.ws.client.ClientTransportException: The server sent HTTP status code 401: Unauthorized

### ISSUE THREAD

**Issue by francescodiperna** [phax/phoss-smp#255]
Good morning, when I add a new partecipant I got the following error.
I'm using the version 7.0.0 and the certificate are ok from the administration interface (I attach a screenshot).
I tryed with another peppol id but I gor the same error.
I'm using the SMK (not production).
Please help me.

Francesco
```

2023-09-18T10:11:22,915] [SMP-SERVER] [INFO ] [http-nio-8080-exec-7] Performing SML query to 'https://acc.edelivery.tech.ec.europa.eu/edelivery-sml/manageparticipantidentifier' -- com.helger.phoss.smp.smlhook.RegistrationHookWriteToSML._createSMLCaller(RegistrationHookWriteToSML.java:67)
[2023-09-18T10:11:23,021] [SMP-SERVER] [INFO ] [http-nio-8080-exec-7] Trying to create new participant iso6523-actorid-upis::0211:92057830678 in SMP 'ZENPROV-SMP' -- com.helger.peppol.smlclient.ManageParticipantIdentifierServiceCaller.create(ManageParticipantIdentifierServiceCaller.java:168)
JAXP: find factoryId =javax.xml.stream.XMLInputFactory
[2023-09-18T10:11:23,716] [SMP-SERVER] [ERROR] [http-nio-8080-exec-7] An exception was thrown -- com.helger.commons.log.LogHelper.log(LogHelper.java:315)
java.sql.SQLException: Caught exception while perfoming something in a level 1 transaction [45]
	at com.helger.db.jdbc.executor.DBExecutor.lambda$performInTransaction$9(DBExecutor.java:652) ~[ph-db-jdbc-7.0.1.jar:7.0.1]
	at com.helger.db.jdbc.executor.DBExecutor.withExistingConnectionDo(DBExecutor.java:541) ~[ph-db-jdbc-7.0.1.jar:7.0.1]
	at com.helger.db.jdbc.executor.DBExecutor.withNewConnectionDo(DBExecutor.java:486) ~[ph-db-jdbc-7.0.1.jar:7.0.1]
	at com.helger.db.jdbc.executor.DBExecutor.performInTransaction(DBExecutor.java:673) [ph-db-jdbc-7.0.1.jar:7.0.1]
	at com.helger.phoss.smp.backend.sql.mgr.SMPServiceGroupManagerJDBC.createSMPServiceGroup(SMPServiceGroupManagerJDBC.java:142) [phoss-smp-backend-sql-7.0.0.jar:7.0.0]
	at com.helger.phoss.smp.backend.sql.mgr.SMPServiceGroupManagerJDBC.createSMPServiceGroup(SMPServiceGroupManagerJDBC.java:74) [phoss-smp-backend-sql-7.0.0.jar:7.0.0]
	at com.helger.phoss.smp.restapi.SMPServerAPI.saveServiceGroup(SMPServerAPI.java:312) [phoss-smp-backend-7.0.0.jar:7.0.0]
	at com.helger.phoss.smp.rest.APIExecutorServiceGroupPut.invokeAPI(APIExecutorServiceGroupPut.java:83) [phoss-smp-webapp-7.0.0.jar:7.0.0]
	at com.helger.photon.api.InvokableAPIDescriptor.invokeAPI(InvokableAPIDescriptor.java:201) [ph-oton-api-9.1.0.jar:9.1.0]
	at com.helger.photon.api.APIInvoker.invoke(APIInvoker.java:74) [ph-oton-api-9.1.0.jar:9.1.0]
	at com.helger.phoss.smp.rest.SMPRestFilter.onFilterBefore(SMPRestFilter.java:381) [phoss-smp-webapp-7.0.0.jar:7.0.0]
	at com.helger.xservlet.AbstractXFilterUnifiedResponse.onFilterBefore(AbstractXFilterUnifiedResponse.java:98) [ph-xservlet-10.1.1.jar:10.1.1]
	at com.helger.xservlet.AbstractXFilter.doHttpFilter(AbstractXFilter.java:186) [ph-xservlet-10.1.1.jar:10.1.1]
	at com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66) [ph-servlet-10.1.1.jar:10.1.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) [catalina.jar:10.1.12]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) [catalina.jar:10.1.12]
	at com.helger.servlet.filter.CharacterEncodingFilter.doHttpFilter(CharacterEncodingFilter.java:184) [ph-servlet-10.1.1.jar:10.1.1]
	at com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66) [ph-servlet-10.1.1.jar:10.1.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) [catalina.jar:10.1.12]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) [catalina.jar:10.1.12]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) [catalina.jar:10.1.12]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [catalina.jar:10.1.12]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) [catalina.jar:10.1.12]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) [catalina.jar:10.1.12]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [catalina.jar:10.1.12]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:676) [catalina.jar:10.1.12]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:10.1.12]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) [catalina.jar:10.1.12]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) [tomcat-coyote.jar:10.1.12]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-coyote.jar:10.1.12]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) [tomcat-coyote.jar:10.1.12]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740) [tomcat-coyote.jar:10.1.12]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-coyote.jar:10.1.12]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:10.1.12]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:10.1.12]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:10.1.12]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.helger.phoss.smp.smlhook.RegistrationHookException: Could not create business iso6523-actorid-upis::0211:92057830678 in SML
	at com.helger.phoss.smp.smlhook.RegistrationHookWriteToSML.createServiceGroup(RegistrationHookWriteToSML.java:132) ~[phoss-smp-backend-7.0.0.jar:7.0.0]
	at com.helger.phoss.smp.backend.sql.mgr.SMPServiceGroupManagerJDBC.lambda$createSMPServiceGroup$0(SMPServiceGroupManagerJDBC.java:154) ~[phoss-smp-backend-sql-7.0.0.jar:7.0.0]
	at com.helger.db.jdbc.executor.DBExecutor.lambda$performInTransaction$9(DBExecutor.java:604) ~[ph-db-jdbc-7.0.1.jar:7.0.1]
	... 36 more
Caused by: com.sun.xml.ws.client.ClientTransportException: The server sent HTTP status code 401: Unauthorized
	at com.sun.xml.ws.transport.http.client.HttpTransportPipe.checkStatusCode(HttpTransportPipe.java:318) ~[jaxws-rt-4.0.1.jar:4.0.1]
	at com.sun.xml.ws.transport.http.client.HttpTransportPipe.createResponsePacket(HttpTransportPipe.java:260) ~[jaxws-rt-4.0.1.jar:4.0.1]
	at com.sun.xml.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:218) ~[jaxws-rt-4.0.1.jar:4.0.1]
	at com.sun.xml.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:131) ~[jaxws-rt-4.0.1.jar:4.0.1]
	at com.sun.xml.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:111) ~[jaxws-rt-4.0.1.jar:4.0.1]
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1106) ~[jaxws-rt-4.0.1.jar:4.0.1]
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1020) ~[jaxws-rt-4.0.1.jar:4.0.1]
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:989) ~[jaxws-rt-4.0.1.jar:4.0.1]
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:847) ~[jaxws-rt-4.0.1.jar:4.0.1]
	at com.sun.xml.ws.client.Stub.process(Stub.java:431) ~[jaxws-rt-4.0.1.jar:4.0.1]
	at com.sun.xml.ws.client.sei.SEIStub.doProcess(SEIStub.java:160) ~[jaxws-rt-4.0.1.jar:4.0.1]
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78) ~[jaxws-rt-4.0.1.jar:4.0.1]
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:62) ~[jaxws-rt-4.0.1.jar:4.0.1]
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:132) ~[jaxws-rt-4.0.1.jar:4.0.1]
	at jdk.proxy3.$Proxy65.create(Unknown Source) ~[?:?]
	at com.helger.peppol.smlclient.ManageParticipantIdentifierServiceCaller.create(ManageParticipantIdentifierServiceCaller.java:173) ~[peppol-sml-client-9.0.3.jar:9.0.3]
	at com.helger.peppol.smlclient.ManageParticipantIdentifierServiceCaller.create(ManageParticipantIdentifierServiceCaller.java:139) ~[peppol-sml-client-9.0.3.jar:9.0.3]
	at com.helger.phoss.smp.smlhook.RegistrationHookWriteToSML.createServiceGroup(RegistrationHookWriteToSML.java:120) ~[phoss-smp-backend-7.0.0.jar:7.0.0]
	at com.helger.phoss.smp.backend.sql.mgr.SMPServiceGroupManagerJDBC.lambda$createSMPServiceGroup$0(SMPServiceGroupManagerJDBC.java:154) ~[phoss-smp-backend-sql-7.0.0.jar:7.0.0]
	at com.helger.db.jdbc.executor.DBExecutor.lambda$performInTransaction$9(DBExecutor.java:604) ~[ph-db-jdbc-7.0.1.jar:7.0.1]
	... 36 more
[2023-09-18T10:11:23,717] [SMP-SERVER] [INFO ] [http-nio-8080-exec-7] Now closing SQL Connection [3768] 2060382711, URL=jdbc:postgresql://postgres-postgresql:5432/zensmpdb, PostgreSQL JDBC Driver -- com.helger.db.jdbc.executor.DBExecutor.debugLog(DBExecutor.java:184)

```

**Comment by francescodiperna** [comment]
![Schermata del 2023-09-18 10-14-39](https://github.com/phax/phoss-smp/assets/91900123/3c0a0df9-a056-4228-8954-f90c80234260)

**Comment by francescodiperna** [comment]
When I try to register with the web application I got the error attached (the ip and url is changed only for this message).
[](url)
![Schermata del 2023-09-19 09-24-59](https://github.com/phax/phoss-smp/assets/91900123/7ba06e3d-510b-4bf3-b7c0-66ddf354f548)

Thanks

**Comment by francescodiperna** [comment]
> Hi @francescodiperna
> 
> * Did you recently change your Peppol SMP certificate?
> * Did you recently change anything else?
> 
> Please see https://github.com/phax/phoss-smp/wiki/SML-notes for a list of known errors regarding the SMP-SML connection. hth

Good morning Philip, yes we have renewed the certificate recently and upgraded the Phoss version.

**Comment by phax** [comment]
Ah okay, then you missed the correct processing for updating a certificate.
Your Peppol SMP certificate is the "key" for the trust between the SMP and the SML.
Please see and read the detailed step by step guideline at https://peppol.helger.com/public/locale-en_US/menuitem-docs-peppol-cert-update#smp

If you old certificate is still valid, you may re-install your old certificate, run the "SML certificate update" step, and then re-install the new certificate.

**Comment by phax** [comment]
Super. So on production, you simply cannot create or delete participants until the date you mentioned - besides that no limitations are available - all SMP queries will work as usual.
