### ISSUE TITLE
Error deleting a service group via REST

### ISSUE THREAD

**Issue by thomas-cito** [phax/phoss-smp#279]
Hello,

I am experiencing a an SQL and 404 error deleting a service group via REST using curl. I tried GET and all fine. Here is something from the log:

```bash
[2024-06-04T15:31:27,312] [SMP-SERVER] [WARN ] [http-nio-8080-exec-1] [SMP REST API] DELETE /iso6523-actorid-upis::0204:99000000-00144-41 ERROR - Failed to delete ServiceGroup 'iso6523-actorid-upis::0204:99000000-00144-41' -- com.helger.phoss.smp.restapi.SMPServerAPI.deleteServiceGroup(SMPServerAPI.java:380)
[2024-06-04T15:31:27,313] [SMP-SERVER] [ERROR] [http-nio-8080-exec-1] [REST API] Internal error -- com.helger.phoss.smp.rest.SMPRestExceptionMapper._logRestException(SMPRestExceptionMapper.java:65)
com.helger.phoss.smp.exception.SMPInternalErrorException: Failed to delete ServiceGroup 'iso6523-actorid-upis::0204:99000000-00144-41'
        at com.helger.phoss.smp.backend.sql.mgr.SMPServiceGroupManagerJDBC.deleteSMPServiceGroup(SMPServiceGroupManagerJDBC.java:356) ~[phoss-smp-backend-sql-5.6.1.jar:5.6.1]
        at com.helger.phoss.smp.restapi.SMPServerAPI.deleteServiceGroup(SMPServerAPI.java:369) ~[phoss-smp-backend-5.6.1.jar:5.6.1]
        at com.helger.phoss.smp.rest.APIExecutorServiceGroupDelete.invokeAPI(APIExecutorServiceGroupDelete.java:60) ~[phoss-smp-webapp-5.6.1.jar:5.6.1]
        at com.helger.photon.api.InvokableAPIDescriptor.invokeAPI(InvokableAPIDescriptor.java:201) ~[ph-oton-api-8.3.6.jar:8.3.6]
        at com.helger.photon.api.APIInvoker.invoke(APIInvoker.java:74) [ph-oton-api-8.3.6.jar:8.3.6]
        at com.helger.phoss.smp.rest.SMPRestFilter.onFilterBefore(SMPRestFilter.java:345) [phoss-smp-webapp-5.6.1.jar:5.6.1]
        at com.helger.xservlet.AbstractXFilterUnifiedResponse.onFilterBefore(AbstractXFilterUnifiedResponse.java:97) [ph-xservlet-9.6.3.jar:9.6.3]
        at com.helger.xservlet.AbstractXFilter.doHttpFilter(AbstractXFilter.java:185) [ph-xservlet-9.6.3.jar:9.6.3]
        at com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66) [ph-servlet-9.6.3.jar:9.6.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.45]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.45]
        at com.helger.servlet.filter.CharacterEncodingFilter.doHttpFilter(CharacterEncodingFilter.java:187) [ph-servlet-9.6.3.jar:9.6.3]
        at com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66) [ph-servlet-9.6.3.jar:9.6.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.45]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.45]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.45]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:9.0.45]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [catalina.jar:9.0.45]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [catalina.jar:9.0.45]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.45]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [catalina.jar:9.0.45]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:9.0.45]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [catalina.jar:9.0.45]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-coyote.jar:9.0.45]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.45]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-coyote.jar:9.0.45]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) [tomcat-coyote.jar:9.0.45]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.45]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.sql.SQLException: Caught exception while perfoming something in a level 1 transaction [10]
        at com.helger.db.jdbc.executor.DBExecutor.lambda$performInTransaction$9(DBExecutor.java:652) ~[ph-db-jdbc-6.7.4.jar:6.7.4]
        at com.helger.db.jdbc.executor.DBExecutor.withExistingConnectionDo(DBExecutor.java:541) ~[ph-db-jdbc-6.7.4.jar:6.7.4]
        at com.helger.db.jdbc.executor.DBExecutor.withNewConnectionDo(DBExecutor.java:486) ~[ph-db-jdbc-6.7.4.jar:6.7.4]
        at com.helger.db.jdbc.executor.DBExecutor.performInTransaction(DBExecutor.java:673) ~[ph-db-jdbc-6.7.4.jar:6.7.4]
        at com.helger.phoss.smp.backend.sql.mgr.SMPServiceGroupManagerJDBC.deleteSMPServiceGroup(SMPServiceGroupManagerJDBC.java:307) ~[phoss-smp-backend-sql-5.6.1.jar:5.6.1]
        ... 31 more
Caused by: com.helger.phoss.smp.smlhook.RegistrationHookException: Could not delete business iso6523-actorid-upis::0204:99000000-00144-41 from SML.
        at com.helger.phoss.smp.smlhook.RegistrationHookWriteToSML.deleteServiceGroup(RegistrationHookWriteToSML.java:184) ~[phoss-smp-backend-5.6.1.jar:5.6.1]
        at com.helger.phoss.smp.backend.sql.mgr.SMPServiceGroupManagerJDBC.lambda$deleteSMPServiceGroup$4(SMPServiceGroupManagerJDBC.java:317) ~[phoss-smp-backend-sql-5.6.1.jar:5.6.1]
        at com.helger.db.jdbc.executor.DBExecutor.lambda$performInTransaction$9(DBExecutor.java:604) ~[ph-db-jdbc-6.7.4.jar:6.7.4]
        at com.helger.db.jdbc.executor.DBExecutor.withExistingConnectionDo(DBExecutor.java:541) ~[ph-db-jdbc-6.7.4.jar:6.7.4]
        at com.helger.db.jdbc.executor.DBExecutor.withNewConnectionDo(DBExecutor.java:486) ~[ph-db-jdbc-6.7.4.jar:6.7.4]
        at com.helger.db.jdbc.executor.DBExecutor.performInTransaction(DBExecutor.java:673) ~[ph-db-jdbc-6.7.4.jar:6.7.4]
        at com.helger.phoss.smp.backend.sql.mgr.SMPServiceGroupManagerJDBC.deleteSMPServiceGroup(SMPServiceGroupManagerJDBC.java:307) ~[phoss-smp-backend-sql-5.6.1.jar:5.6.1]
        ... 31 more
Caused by: com.sun.xml.ws.client.ClientTransportException: The server sent HTTP status code 404: Not Found
        at com.sun.xml.ws.transport.http.client.HttpTransportPipe.checkStatusCode(HttpTransportPipe.java:307) ~[jaxws-rt-2.3.5.jar:2.3.5]
        at com.sun.xml.ws.transport.http.client.HttpTransportPipe.createResponsePacket(HttpTransportPipe.java:249) ~[jaxws-rt-2.3.5.jar:2.3.5]
        at com.sun.xml.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:207) ~[jaxws-rt-2.3.5.jar:2.3.5]
        at com.sun.xml.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:120) ~[jaxws-rt-2.3.5.jar:2.3.5]
        at com.sun.xml.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:109) ~[jaxws-rt-2.3.5.jar:2.3.5]
        at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1105) ~[jaxws-rt-2.3.5.jar:2.3.5]
        at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1019) ~[jaxws-rt-2.3.5.jar:2.3.5]
        at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:988) ~[jaxws-rt-2.3.5.jar:2.3.5]
        at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:846) ~[jaxws-rt-2.3.5.jar:2.3.5]
        at com.sun.xml.ws.client.Stub.process(Stub.java:432) ~[jaxws-rt-2.3.5.jar:2.3.5]
        at com.sun.xml.ws.client.sei.SEIStub.doProcess(SEIStub.java:161) ~[jaxws-rt-2.3.5.jar:2.3.5]
        at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77) ~[jaxws-rt-2.3.5.jar:2.3.5]
        at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:61) ~[jaxws-rt-2.3.5.jar:2.3.5]
        at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:131) ~[jaxws-rt-2.3.5.jar:2.3.5]
        at com.sun.proxy.$Proxy112.delete(Unknown Source) ~[?:?]
        at com.helger.peppol.smlclient.ManageParticipantIdentifierServiceCaller.delete(ManageParticipantIdentifierServiceCaller.java:286) ~[peppol-sml-client-8.7.1.jar:8.7.1]
        at com.helger.peppol.smlclient.ManageParticipantIdentifierServiceCaller.delete(ManageParticipantIdentifierServiceCaller.java:256) ~[peppol-sml-client-8.7.1.jar:8.7.1]
        at com.helger.phoss.smp.smlhook.RegistrationHookWriteToSML.deleteServiceGroup(RegistrationHookWriteToSML.java:172) ~[phoss-smp-backend-5.6.1.jar:5.6.1]
        at com.helger.phoss.smp.backend.sql.mgr.SMPServiceGroupManagerJDBC.lambda$deleteSMPServiceGroup$4(SMPServiceGroupManagerJDBC.java:317) ~[phoss-smp-backend-sql-5.6.1.jar:5.6.1]
        at com.helger.db.jdbc.executor.DBExecutor.lambda$performInTransaction$9(DBExecutor.java:604) ~[ph-db-jdbc-6.7.4.jar:6.7.4]
        at com.helger.db.jdbc.executor.DBExecutor.withExistingConnectionDo(DBExecutor.java:541) ~[ph-db-jdbc-6.7.4.jar:6.7.4]
        at com.helger.db.jdbc.executor.DBExecutor.withNewConnectionDo(DBExecutor.java:486) ~[ph-db-jdbc-6.7.4.jar:6.7.4]
        at com.helger.db.jdbc.executor.DBExecutor.performInTransaction(DBExecutor.java:673) ~[ph-db-jdbc-6.7.4.jar:6.7.4]
        at com.helger.phoss.smp.backend.sql.mgr.SMPServiceGroupManagerJDBC.deleteSMPServiceGroup(SMPServiceGroupManagerJDBC.java:307) ~[phoss-smp-backend-sql-5.6.1.jar:5.6.1]
        ... 31 more
[2024-06-04T15:31:27,317] [SMP-SERVER] [WARN ] [http-nio-8080-exec-1] Finished invoking API '/iso6523-actorid-upis%3A%3A0204%3A99000000-00144-41' which took 3118 milliseconds (which is too long) -- com.helger.photon.api.callback.LoggingAPILongRunningExecutionCallback.onLongRunningExecution(LoggingAPILongRunningExecutionCallback.java:39)
```

Thanks and kind regards,

Thomas

**Comment by phax** [comment]
The SML denied the deletion of the participant. Possible reasons are e.g.:
* you don't own the Participant
* your certificate is expired
* the participant does not exist in the SML at all (being the most likely one for 404)

Please check e.g. with peppol.helger.com if the participant is registered to your SMP or not

**Comment by phax** [comment]
So in this case you have a participant only in your SMP but non in the SML. To solve that issues, do the following steps in the GUI:
1. Login and go to "Administration / SMP Settings"
2. Uncheck "SML enabled" and save
3. Go to "Service Groups" page and delete the service group in question - this will delete it only locally
4. Go back to "Administration / SMP Settings"
5. Re-check "SML enabled" again
6. Problem solved.

hth

**Comment by thomas-cito** [comment]
This was actually the first we tried, now we have the little script that does it in both case, when the participant is on the SML/ SMK or also when not. And we get a nice 500 or 200 status back. Thanks a lot!
