### ISSUE TITLE
Problem deploying SMP version 7.1.4

### ISSUE THREAD

**Issue by Robcio35** [phax/phoss-smp#286]
Hello,
I just tried to deploy the SMP version 7.1.4 on my Linux server (Ubuntu) with Tomcat 10.x.
I first downloaded the binary phoss-smp-webapp-xml-7.1.4.war.
Then I renamed the phoss-smp-webapp-xml-7.1.4.war to phoss.war.
When deploying the phoss.war file, some errors are notified in catalina.out :
_02-Aug-2024 00:04:30.567 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/10.1.26
02-Aug-2024 00:04:30.569 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jul 7 2024 21:02:13 UTC
02-Aug-2024 00:04:30.570 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 10.1.26.0
02-Aug-2024 00:04:30.570 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
02-Aug-2024 00:04:30.570 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            6.8.0-39-generic
02-Aug-2024 00:04:30.570 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
02-Aug-2024 00:04:30.570 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-21-openjdk-amd64
02-Aug-2024 00:04:30.570 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           21.0.4+7-Ubuntu-1ubuntu224.04
02-Aug-2024 00:04:30.570 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Ubuntu
02-Aug-2024 00:04:30.570 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /opt/tomcat
02-Aug-2024 00:04:30.570 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /opt/tomcat
02-Aug-2024 00:04:30.577 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/opt/tomcat/conf/logging.properties
02-Aug-2024 00:04:30.577 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
02-Aug-2024 00:04:30.577 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.security.egd=file:///dev/urandom
02-Aug-2024 00:04:30.577 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
02-Aug-2024 00:04:30.577 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
02-Aug-2024 00:04:30.577 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms128m
02-Aug-2024 00:04:30.577 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx1024m
02-Aug-2024 00:04:30.578 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
02-Aug-2024 00:04:30.578 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
02-Aug-2024 00:04:30.578 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
02-Aug-2024 00:04:30.578 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
02-Aug-2024 00:04:30.578 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
02-Aug-2024 00:04:30.578 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
02-Aug-2024 00:04:30.578 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
02-Aug-2024 00:04:30.578 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
02-Aug-2024 00:04:30.578 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms512M
02-Aug-2024 00:04:30.579 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx1024M
02-Aug-2024 00:04:30.579 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseParallelGC
02-Aug-2024 00:04:30.579 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true
02-Aug-2024 00:04:30.579 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/opt/tomcat
02-Aug-2024 00:04:30.579 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/opt/tomcat
02-Aug-2024 00:04:30.579 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/opt/tomcat/temp
02-Aug-2024 00:04:30.581 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [2.0.7] using APR version [1.7.2].
02-Aug-2024 00:04:30.583 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 3.0.13 30 Jan 2024]
02-Aug-2024 00:04:30.778 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-80"]
02-Aug-2024 00:04:30.799 INFO [main] org.apache.coyote.http11.AbstractHttp11Protocol.configureUpgradeProtocol The ["https-openssl-nio2-443"] connector has been configured to support negotiation to [h2] via ALPN
02-Aug-2024 00:04:30.799 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["https-openssl-nio2-443"]
02-Aug-2024 00:04:30.907 INFO [main] org.apache.tomcat.util.net.AbstractEndpoint.logCertificate Connector [https-openssl-nio2-443], TLS virtual host [_default_], certificate type [RSA] configured from key [/opt/tomcat/conf/server.key], certificate [/etc/ssl/certs/server.crt] and certificate chain [/etc/ssl/certs/ca_bundle.crt] with trust store [null]
02-Aug-2024 00:04:30.911 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [479] milliseconds
02-Aug-2024 00:04:30.939 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
02-Aug-2024 00:04:30.939 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/10.1.26]
02-Aug-2024 00:04:30.954 WARNING [main] org.apache.catalina.core.StandardContext.setPath A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [/] does not meet these criteria and has been changed to []
02-Aug-2024 00:04:30.955 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/opt/tomcat/webapps/phoss.war]
02-Aug-2024 00:04:30.962 WARNING [main] org.apache.tomcat.util.digester.SetPropertiesRule.begin Match [Context] failed to set property [antiJARLocking] to [true]
02-Aug-2024 00:04:32.237 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
[2024-08-02T00:04:32,512] [SMP-SERVER] [INFO ] [main] Registering default ph-oton listeners and servlets -- com.helger.photon.bootstrap4.stub.init.PhotonStubServletInitializer.registerServlets(PhotonStubServletInitializer.java:92)
[2024-08-02T00:04:32,525] [SMP-SERVER] [INFO ] [main] Finished registering default ph-oton listeners and servlets -- com.helger.photon.bootstrap4.stub.init.PhotonStubServletInitializer.registerServlets(PhotonStubServletInitializer.java:187)
[2024-08-02T00:04:32,615] [SMP-SERVER] [INFO ] [main] Set default timezone to 'UTC' -- com.helger.phoss.smp.servlet.SMPWebAppListener._initTimeZone(SMPWebAppListener.java:169)
[2024-08-02T00:04:32,622] [SMP-SERVER] [INFO ] [main]        _                 _               -- com.helger.photon.core.servlet.WebAppListener.logLogo(WebAppListener.java:181)
[2024-08-02T00:04:32,622] [SMP-SERVER] [INFO ] [main]  _ __ | |__         ___ | |_ ___  _ __   -- com.helger.photon.core.servlet.WebAppListener.logLogo(WebAppListener.java:182)
[2024-08-02T00:04:32,622] [SMP-SERVER] [INFO ] [main] | '_ \| '_ \ _____ / _ \| __/ _ \| '_ \  -- com.helger.photon.core.servlet.WebAppListener.logLogo(WebAppListener.java:183)
[2024-08-02T00:04:32,622] [SMP-SERVER] [INFO ] [main] | |_) | | | |_____| (_) | || (_) | | | | -- com.helger.photon.core.servlet.WebAppListener.logLogo(WebAppListener.java:184)
[2024-08-02T00:04:32,622] [SMP-SERVER] [INFO ] [main] | .__/|_| |_|      \___/ \__\___/|_| |_| -- com.helger.photon.core.servlet.WebAppListener.logLogo(WebAppListener.java:185)
[2024-08-02T00:04:32,624] [SMP-SERVER] [INFO ] [main] |_|                               v9.2.5 -- com.helger.photon.core.servlet.WebAppListener.logLogo(WebAppListener.java:189)
[2024-08-02T00:04:32,630] [SMP-SERVER] [INFO ] [main] Java 21.0.4 running 'phoss SMP (XML backend)' on Apache Tomcat/10.1.26 with 910MB max RAM and Servlet API 6.0 -- com.helger.photon.core.servlet.WebAppListener.logServerInfo(WebAppListener.java:195)
[2024-08-02T00:04:32,632] [SMP-SERVER] [INFO ] [main] No servlet context init-parameters present -- com.helger.photon.core.servlet.WebAppListener.logInitParameters(WebAppListener.java:241)
[2024-08-02T00:04:32,649] [SMP-SERVER] [INFO ] [main] Using the following third party modules: -- com.helger.photon.core.servlet.WebAppListener.logThirdpartyModules(WebAppListener.java:258)
[2024-08-02T00:04:32,674] [SMP-SERVER] [INFO ] [main]   Apache HttpComponents Client 5.3.1 licensed under Apache License 2 -- com.helger.photon.core.servlet.WebAppListener.logThirdpartyModules(WebAppListener.java:268)
[2024-08-02T00:04:32,674] [SMP-SERVER] [INFO ] [main]   Apache HttpComponents Core 5.2.5 licensed under Apache License 2 -- com.helger.photon.core.servlet.WebAppListener.logThirdpartyModules(WebAppListener.java:268)
[2024-08-02T00:04:32,674] [SMP-SERVER] [INFO ] [main]   Apache Log4j 2 2.23.1 licensed under Apache License 2 -- com.helger.photon.core.servlet.WebAppListener.logThirdpartyModules(WebAppListener.java:268)
[2024-08-02T00:04:32,674] [SMP-SERVER] [INFO ] [main]   Apache Santuario 3.0.4 licensed under Apache License 2 -- com.helger.photon.core.servlet.WebAppListener.logThirdpartyModules(WebAppListener.java:268)
[2024-08-02T00:04:32,674] [SMP-SERVER] [INFO ] [main]   Base64 2.3.7 licensed under Public Domain -- com.helger.photon.core.servlet.WebAppListener.logThirdpartyModules(WebAppListener.java:268)
[2024-08-02T00:04:32,674] [SMP-SERVER] [INFO ] [main]   Bootstrap 4.6.2 licensed under MIT License -- com.helger.photon.core.servlet.WebAppListener.logThirdpartyModules(WebAppListener.java:268)
[2024-08-02T00:04:32,674] [SMP-SERVER] [INFO ] [main]   Bootstrap Datetime Picker 2.4.4 licensed under Apache License 2 -- com.helger.photon.core.servlet.WebAppListener.logThirdpartyModules(WebAppListener.java:268)
[2024-08-02T00:04:32,674] [SMP-SERVER] [INFO ] [main]   Bouncy Castle 1.78.0 licensed under MIT License -- com.helger.photon.core.servlet.WebAppListener.logThirdpartyModules(WebAppListener.java:268)
[2024-08-02T00:04:32,675] [SMP-SERVER] [INFO ] [main]   dnsjava 3.5.3 licensed under BSD 2-Clause License -- com.helger.photon.core.servlet.WebAppListener.logThirdpartyModules(WebAppListener.java:268)
[2024-08-02T00:04:32,675] [SMP-SERVER] [INFO ] [main]   FindBugs JSR305 and annotations 3.0.2 licensed under Apache License 2 -- com.helger.photon.core.servlet.WebAppListener.logThirdpartyModules(WebAppListener.java:268)
[2024-08-02T00:04:32,675] [SMP-SERVER] [INFO ] [main]   Jakarta Mail 1.6.7 licensed under Eclipse Public License 2 -- com.helger.photon.core.servlet.WebAppListener.logThirdpartyModules(WebAppListener.java:268)
[2024-08-02T00:04:32,675] [SMP-SERVER] [INFO ] [main]   Quartz 2.2.3 licensed under Apache License 2 -- com.helger.photon.core.servlet.WebAppListener.logThirdpartyModules(WebAppListener.java:268)
[2024-08-02T00:04:32,675] [SMP-SERVER] [INFO ] [main]   SLF4J API 2.0.9 licensed under MIT License -- com.helger.photon.core.servlet.WebAppListener.logThirdpartyModules(WebAppListener.java:268)
[2024-08-02T00:04:32,768] [SMP-SERVER] [INFO ] [main] Using '/generated' as the data path -- com.helger.photon.io.WebFileIO.initPaths(WebFileIO.java:92)
[2024-08-02T00:04:32,772] [SMP-SERVER] [WARN ] [main] File operation CREATE_DIR_RECURSIVE failed with error code SOURCE_PARENT_NOT_WRITABLE on '/generated' -- com.helger.commons.io.file.LoggingFileOperationCallback.onError(LoggingFileOperationCallback.java:57)
[2024-08-02T00:04:32,772] [SMP-SERVER] [ERROR] [main] Context Initialization Error -- com.helger.photon.core.servlet.WebAppListener.contextInitialized(WebAppListener.java:745)
com.helger.commons.exception.InitializationException: The passed base path /generated exists but is not a directory!
        at com.helger.commons.io.relative.FileRelativeIO.<init>(FileRelativeIO.java:102) ~[ph-commons-11.1.6.jar:11.1.6]
        at com.helger.photon.io.WebFileIO.initPaths(WebFileIO.java:94) ~[ph-oton-io-9.2.5.jar:9.2.5]
        at com.helger.photon.core.servlet.WebAppListener.initPaths(WebAppListener.java:496) ~[ph-oton-core-9.2.5.jar:9.2.5]
        at com.helger.photon.core.servlet.WebAppListener.contextInitialized(WebAppListener.java:691) [ph-oton-core-9.2.5.jar:9.2.5]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:3997) [catalina.jar:10.1.26]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4424) [catalina.jar:10.1.26]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) [catalina.jar:10.1.26]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:599) [catalina.jar:10.1.26]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:571) [catalina.jar:10.1.26]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:654) [catalina.jar:10.1.26]
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:969) [catalina.jar:10.1.26]
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1911) [catalina.jar:10.1.26]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) [?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) [?:?]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:10.1.26]
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) [?:?]
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:771) [catalina.jar:10.1.26]
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:423) [catalina.jar:10.1.26]
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1629) [catalina.jar:10.1.26]
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:303) [catalina.jar:10.1.26]
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:109) [catalina.jar:10.1.26]
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:385) [catalina.jar:10.1.26]
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:332) [catalina.jar:10.1.26]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:776) [catalina.jar:10.1.26]
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:772) [catalina.jar:10.1.26]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) [catalina.jar:10.1.26]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1203) [catalina.jar:10.1.26]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1193) [catalina.jar:10.1.26]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) [?:?]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:10.1.26]
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145) [?:?]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:749) [catalina.jar:10.1.26]
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:203) [catalina.jar:10.1.26]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) [catalina.jar:10.1.26]
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:415) [catalina.jar:10.1.26]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) [catalina.jar:10.1.26]
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:874) [catalina.jar:10.1.26]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164) [catalina.jar:10.1.26]
        at org.apache.catalina.startup.Catalina.start(Catalina.java:757) [catalina.jar:10.1.26]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345) [bootstrap.jar:10.1.26]
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473) [bootstrap.jar:10.1.26]
[2024-08-02T00:04:32,866] [SMP-SERVER] [INFO ] [main] Default application ID set to 'public' -- com.helger.photon.core.appid.PhotonGlobalState.lambda$setDefaultApplicationID$1(PhotonGlobalState.java:92)
02-Aug-2024 00:04:32.921 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
02-Aug-2024 00:04:32.923 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/phoss] startup failed due to previous errors
[2024-08-02T00:04:32,924] [SMP-SERVER] [INFO ] [main] Servlet context 'phoss SMP (XML backend)' is being destroyed -- com.helger.photon.core.servlet.WebAppListener.contextDestroyed(WebAppListener.java:868)
[2024-08-02T00:04:32,942] [SMP-SERVER] [ERROR] [main] Not writing statistics because WebFileIO was not initialized! -- com.helger.photon.core.servlet.WebAppListener.handleStatisticsOnEnd(WebAppListener.java:856)
[2024-08-02T00:04:32,958] [SMP-SERVER] [INFO ] [main] Servlet context 'phoss SMP (XML backend)' was destroyed in 32 milli seconds -- com.helger.photon.core.servlet.WebAppListener.contextDestroyed(WebAppListener.java:890)
02-Aug-2024 00:04:32.964 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/opt/tomcat/webapps/phoss.war] has finished in [2,009] ms
02-Aug-2024 00:04:32.965 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/examples]
02-Aug-2024 00:04:33.067 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
02-Aug-2024 00:04:33.087 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/examples] has finished in [122] ms
02-Aug-2024 00:04:33.087 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/host-manager]
02-Aug-2024 00:04:33.111 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
02-Aug-2024 00:04:33.114 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/host-manager] has finished in [27] ms
02-Aug-2024 00:04:33.114 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/manager]
02-Aug-2024 00:04:33.136 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
02-Aug-2024 00:04:33.137 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/manager] has finished in [23] ms
02-Aug-2024 00:04:33.137 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/docs]
02-Aug-2024 00:04:33.155 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
02-Aug-2024 00:04:33.156 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/docs] has finished in [19] ms
02-Aug-2024 00:04:33.156 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/ROOT]
02-Aug-2024 00:04:33.170 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
02-Aug-2024 00:04:33.171 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/ROOT] has finished in [15] ms
02-Aug-2024 00:04:33.173 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-80"]
02-Aug-2024 00:04:33.178 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["https-openssl-nio2-443"]
02-Aug-2024 00:04:33.179 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [2267] milliseconds_

I noticed 2 log lines : 
Line 1) [2024-08-02T00:04:32,772] [SMP-SERVER] [WARN ] [main] File operation CREATE_DIR_RECURSIVE failed with error code SOURCE_PARENT_NOT_WRITABLE on '/generated'
Line 2) [2024-08-02T00:04:32,772] [SMP-SERVER] [ERROR] [main] Context Initialization Error -- com.helger.photon.core.servlet.WebAppListener.contextInitialized(WebAppListener.java:745)
com.helger.commons.exception.InitializationException: The passed base path /generated exists but is not a directory!

Could you help me in understanding where I have to pay attention ? 
Where is located the application configuration file ?

Thank you for your help.

Robert

**Comment by phax** [comment]
The base problems of your startup are:
```
[2024-08-02T00:04:32,768] [SMP-SERVER] [INFO ] [main] Using '/generated' as the data path -- com.helger.photon.io.WebFileIO.initPaths(WebFileIO.java:92)
[2024-08-02T00:04:32,772] [SMP-SERVER] [WARN ] [main] File operation CREATE_DIR_RECURSIVE failed with error code SOURCE_PARENT_NOT_WRITABLE on '/generated' -- com.helger.commons.io.file.LoggingFileOperationCallback.onError(LoggingFileOperationCallback.java:57)
```
This means, that you are trying to store some data in `/generated` and your user does not have the right to create this directory.
The configuration file is `application.properties` - see https://github.com/phax/ph-commons/wiki/ph-config for details.

**Comment by Robcio35** [comment]
Thank you Philip.
I changed the value of webapp.datapath in the application.properties and the problem was solved.
